name: Deploy to Single EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Copiar todo o projeto para a EC2
    - name: Copiar código para EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.EC2_USER }}/app"

    # Executar todos os comandos na mesma instância
    - name: Build e executar containers
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          
          # ===== BACKEND =====
          echo "Processando backend..."
          cd backend
          
          # Parar e remover container existente
          docker stop backend-container || true
          docker rm backend-container || true
          
          # Remover imagem antiga
          docker rmi backend-image || true
          
          # Build da nova imagem
          docker build -t backend-image .
          
          # Executar novo container
          docker run -d \
            --name backend-container \
            --restart unless-stopped \
            -p 5000:5000 \
            -v $PWD/data:/app/data \
            backend-image

          # ===== FRONTEND =====
          echo "Processando frontend..."
          cd ../frontend
          
          # Parar e remover container existente
          docker stop frontend-container || true
          docker rm frontend-container || true
          
          # Remover imagem antiga
          docker rmi frontend-image || true
          
          # Build da nova imagem
          docker build -t frontend-image .
          
          # Executar novo container
          docker run -d \
            --name frontend-container \
            --restart unless-stopped \
            -p 3000:80 \
            -e API_BASE_URL=http://localhost:5000 \
            frontend-image

          # Mostrar containers em execução
          echo "Containers ativos:"
          docker ps