name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # === BACKEND - EC2_1 ===
    - name: Copiar backend para EC2 Instance 1
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./backend"
        target: "/home/${{ secrets.EC2_USER }}/backend"

    - name: Verificar arquivos no EC2 Instance 1
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Arquivos no backend:"
          ls -la ~/backend

    - name: Build backend Docker image on EC2 Instance 1
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/backend/backend
          docker rmi backend-image || true
          docker build -t backend-image .

    # === FRONTEND - EC2_2 ===
    - name: Copiar frontend para EC2 Instance 2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./frontend"
        target: "/home/${{ secrets.EC2_USER }}/frontend"

    - name: Verificar arquivos no EC2 Instance 2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Arquivos no frontend:"
          ls -la ~/frontend

    - name: Build frontend Docker image on EC2 Instance 2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/frontend/frontend
          docker rmi frontend-image || true
          docker build -t frontend-image .
